#!/usr/bin/env python
import sys
from mako.template import Template

def main():
    argc = len(sys.argv)
    if argc < 3:
        print "usage: prep file.t file"
        sys.exit(0)

    temp = sys.argv[1]
    file = sys.argv[2]

    temp = Template(open(temp).read())
    temp = temp.render()

    file = open(file, 'w')
    file.write(temp)

if __name__ == "__main__":
    main()
